### ISSUE TITLE
_analysisServerWrapper.restart() leaves the server in a bad state

### ISSUE THREAD

**Issue by devoncarew** [dart-atom/dartlang#22]
You can't shut down the server, start it, shut it down, and start it again successfully. I _think_ the issue is with restart() not recycling some variables properly. Also possibly because the `Future<int> get whenDisposed => _processCompleter.future;` getter returns a single event, when it now could be disposed (shut down) several times.

**Comment by radicaled** [comment]
`Future<int> get whenDisposed => _processCompleter.future;`

We replace `_processCompleter.future` on restart, but other components might still have a reference to the older instance.

This should probably be a `Stream` or a `Property` so that consumers can just listen for changes and act accordingly.
