### ISSUE TITLE
release notes popup appears twice

### ISSUE THREAD

**Issue by skybrian** [dart-atom/dartlang#239]
It seemed like I was seeing the release notes popup rather often, so I did an experiment.

I just upgraded to 0.3.17. After quitting Atom and starting it again, the release notes popup appeared. Then I immediately shut down atom and launched it again, and the same popup appeared again.

I shut it down again and restarted, and it didn't appear the third time.

(Since I use atom on two different machines, that means I'm probably seeing the same release notes popup four times.)

**Comment by devoncarew** [comment]
I'm investigating, but ironically, 0.3.17 contains code to reduce the number of times we show the release notes. We had been storing the last version run on localStorage; for atom, it looks like that data store is based on the dir that atom was launched in.

We switched over to using a hidden pref in the user's config. That is a per-user setting. You can see it in your config file (`_dartlang: _version`).

Really surprised it showed up twice. When you say quit, did you quit atom, or was the plugin uninstalled and re-installed as part of the upgrade process? I ask because we do have an issue with some parts of the old plugin still being active after an upgrade, so the old code to show the changlog notes might have run.

**Comment by skybrian** [comment]
Well, I thought I did. I don't have a way to confirm it now. I guess we can wait and see if it happens again.

**Comment by skybrian** [comment]
I started Atom on my work computer (after not using it in a while) and it showed release notes for an old version of the Dart plugin. Then I went to Preferences-> Packages and clicked on the Upgrade button. It showed the release notes immediately (without rebooting). I then exited and started up, and it showed them again.

Perhaps that's what I did last time.
