### ISSUE TITLE
outline view: move return type somewhere else?

### ISSUE THREAD

**Issue by skybrian** [dart-atom/dartlang#288]
This is subjective, but I think the outline would be prettier if the return type were not listed first. Removing it entirely would be okay (since you can click on the link to show it), or it could go after the parameters like on api.dartlang.org. [1]

Maybe removing both the parameters and the return type would make it easier to scan?

[1] https://api.dartlang.org/1.12.0/dart-core/List-class.html

**Comment by devoncarew** [comment]
Here are two possibilities:

    https://github.com/dart-atom/dartlang/pull/272

One is as it is now, the other is using dartdoc's arrows. I had the arrows at first, but changed to the normal dart syntax after using it for a day or so. W/ the arrows the left edge of the outline looked ragged, because some symbols started with `_` and some didn't.

I'm not set on the current UI; it is slightly harder to scan currently, but has the benefit of a familiar dart syntax. Here's the code: https://github.com/dart-atom/dartlang/blob/master/lib/impl/outline.dart#L203 if you want to play with options.
