### ISSUE TITLE
plugin freezes editor on the angular2 sources

### ISSUE THREAD

**Issue by yjbanov** [dart-atom/dartlang#57]
https://github.com/angular/angular uses a custom file layout that does not follow the pub convention. The plugin attempts to analyze the sources and (naturally) produces lots of warnings. This results in a lot of freezing while typing.

## To reproduce

```bash
git clone git@github.com:angular/angular.git
cd angular
atom .
```

Attempt editing any dart file, e.g. in `modules/angular2/src/transform/di_transformer.dart`.

**Comment by devoncarew** [comment]
It looks like there's a pubspec at the repo root and then 1/2 dozen additional packages in the `modules/` and `modules_dart` dirs. Right now we scan down from the project root looking for dart projects - directories either containing `pubspec.yaml` files or `.packages` files. We stop looking traversing subdirs once we have a matching dir. So, that top-level pubspec means we don't find any of the contained packages.

If I rename that top-level pubspec to something else, we do locate the sub-dir packages. However, when I try and run pub on them, I note that they have some funky interpolation going on:

```
authors:
<%= Object.keys(packageJson.contributors).map(function(name) {
```

I'm not sure how we can best interpret the angular repo from the tools perspective. Would it help to just be able to turn off all analysis for a project?

**Comment by yjbanov** [comment]
A switch to turn off analysis for the current project would help (currently the only option is to disable the plugin globally). The way our code is organized isn't something I expect any tools to understand anyway.

Maybe a `.atom-dart` file at the root with some preferences?

**Comment by devoncarew** [comment]
I'm going to close this issue out - we now handle projects with lots of analysis issues much more efficiently. In addition, if you're on a dev sdk, there are new metadata files you can add to repos in order to filter out files from being analyzed:
- https://github.com/dart-lang/dartdoc/blob/master/.analysis_options
- https://github.com/dart-lang/dartdoc/blob/master/test_package/.analysis_options

Feel free to re-open or file new issues if you think we can handle the angular repo better -
