### ISSUE TITLE
Support debugging Flutter applications running in Mojo shell

### ISSUE THREAD

**Issue by aghassemi** [dart-atom/dartlang#570]
It would be great to have the ability to launch and debug Flutter applications that use `flutter_tools run_mojo` instead of `flutter_tools start`. 

https://github.com/aghassemi/syncbase-flutter-sample is a simple example of such application.

@devoncarew

**Comment by devoncarew** [comment]
Thanks! I'll check out that sample. Hopefully just a small tweak to the existing `flutter` launch type.

**Comment by devoncarew** [comment]
@aghassemi, some work for this has landed.

If you launch a flutter app, we create a `.atom/launches` file for it. If you then edit that file to change references from `flutter` to `mojo`, you'll get a mojo launch config. We'll run that file with `flutter run_mojo` instead of `flutter start`.

```
# Mojo launch configuration for lib/main.dart.
type: mojo
path: lib/main.dart

mojo:
  args:
    - --android
    - --mojo-debug
```

Can you give this a shot and see if you hit any issues?

**Comment by aghassemi** [comment]
Thanks! Will try it and will update here.

**Comment by devoncarew** [comment]
Initial work for this is in -
