### ISSUE TITLE
Autocomplete code not working

### ISSUE THREAD

**Issue by othpiik** [dart-atom/dartlang#942]
Im use Atom 1.7.1
try to coding dart but autocomplete code not working
![screenshot from 2016-04-16 11-46-01](https://cloud.githubusercontent.com/assets/11581180/14579152/198668e8-03c9-11e6-96b5-2fc76f86f035.png)
![screenshot from 2016-04-16 11-46-28](https://cloud.githubusercontent.com/assets/11581180/14579153/199e0750-03c9-11e6-8e50-4836a8c12883.png)
![screenshot from 2016-04-16 11-46-51](https://cloud.githubusercontent.com/assets/11581180/14579154/1a325db0-03c9-11e6-9c4d-dbcceef15770.png)
![screenshot from 2016-04-16 11-47-04](https://cloud.githubusercontent.com/assets/11581180/14579155/1a6db18a-03c9-11e6-975c-5ca6b7de90e9.png)

**Comment by devoncarew** [comment]
Thanks for the report! from that screenshot, it looks like you're working on an unsaved file. You'll need to create a dart project and open a file from it in order to code completion to work. You can create a project using the stagehand tool (http://stagehand.pub/), or a flutter project using the flutter tool (flutter.io). Thanks!
