### ISSUE TITLE
"format on save" option has no effect

### ISSUE THREAD

**Issue by skybrian** [dart-atom/dartlang#944]
To test this, I add an extra blank line to a correct Dart file and then save. It doesn't disappear.

This is using:
  - Atom 1.7.1
 - dart plugin 0.6.10
 - Dart SDK 1.16.0-edge-something

Also tried it with an older Dart SDK (1.4 something).

**Comment by devoncarew** [comment]
I removed this feature in the last release :) It was buggy in that it didn't play well with atom's auto-save feature, and w/ some refactorings. We'll add it back in when it's debugged.

You're still seeing that option because the value is in your config.cson file. If you remove the value from the file (from the command pallette, application: open your config), the setting will disappear from the UI.

**Comment by devoncarew** [comment]
will be fixed by https://github.com/dart-atom/dartlang/pull/963
